name        : lrdf
version     : 0.5.0
release     : 1
source      :
    - https://github.com/swh/LRDF/archive/0.5.0.tar.gz : ba803af936fd53a8b31651043732e6d6cec3d24fa24d2cb8c1506c2d1675e2a2
license     : GPL-2.0
component   : programming
summary     : A lightweight RDF library for accessing plugin metadata in the LADSPA plugin system.
description : A lightweight RDF library for accessing plugin metadata in the LADSPA plugin system.
builddeps   :
    - pkgconfig(raptor2)
setup       : |
    %autogen --disable-static
build       : |
    %make
install     : |
    %make_install
